format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/accessom2_restart.nml
  hashes:
    binhash: 782f7fe04acfe37165893ec626a97409
    md5: 92b541e5a4934e5a1946803d227b6f87
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ice/grid.nc
  hashes:
    binhash: 54597408bd0b7ee22a7071f40b5f670f
    md5: 189f572cf886440edd5ac6dab40df3d8
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ice/i2o.nc
  hashes:
    binhash: dbe98abc3b46b2af7e2a8dfc23b9aadb
    md5: 5ed318c84b6140c9401be3becd68c191
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ice/ice.restart_file
  hashes:
    binhash: 28e646e2953abda293e7c63f80c78d7c
    md5: 4bad71e5de5cbafa56ed2a37be9205a6
work/ice/RESTART/iced.2159-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ice/iced.2159-01-01-00000.nc
  hashes:
    binhash: 5818d3f228c4d92de3b0d53ddcfd9a8e
    md5: a9ce508d96cecbe469d1b0517567ec3b
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ice/kmt.nc
  hashes:
    binhash: 57ecfa371babe4b624e3d100fcccfef2
    md5: a46c01045f519b9002b10f82df6ad376
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ice/monthly_sstsss.nc
  hashes:
    binhash: cdd9032ba794dbd9105d9a9bbb9b16c7
    md5: e00d77cf7b519d9bbcfc8bea2e34ef8f
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ice/o2i.nc
  hashes:
    binhash: a5d0b1c63a11a9c67b2d51ba4470afcb
    md5: b98b1772390564993af05aad8d259557
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ice/sicemass.nc
  hashes:
    binhash: 1bc4355c26e679852b685f4eb496db45
    md5: 8e8b7fa7d3358a4db88b4ac59bb7d023
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ice/u_star.nc
  hashes:
    binhash: 9168dd96709b3cfb7511d4fd8b8d1d54
    md5: 159fc3219754f4228cf4d5e85673b0a9
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ocean/ocean_age.res.nc
  hashes:
    binhash: 3e90605fc799b5be92e8ebf65fd7aa49
    md5: 5325ddbde8707867efcfd08bb2f218a1
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5a239f42f879a43507523157f3256c23
    md5: 056ebd3a9db121a7a63b8ef22586929e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 041e7e0151b0b74c451b2c8ba6af0988
    md5: 03f6c3453442c46c034a74cbf9a3cd2d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ocean/ocean_density.res.nc
  hashes:
    binhash: fff58b7c78186181f0243fb6b20b9946
    md5: 9b8ea55685f9261fdc36bd8b183dc91d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 987219786d4e3d30f7cd1d1e3c29e8d8
    md5: 1a78a48f33d5640178ec0ab4cd610e0b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 849d63de4765191aa44deb668da9c7fd
    md5: 17972103586b3b751f38c506f1abde52
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 842c39509d874305ad1ae621a2d27f03
    md5: 04917eb4cdd97326026e3393c93e05db
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ocean/ocean_solo.res
  hashes:
    binhash: 8b2d50285f00387067e3b01136b96c36
    md5: 1a6ca4a6acc10c121b63949a9ffa53d7
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4e65e4ac10392b415ebf74582eca3589
    md5: ada7d301dd2b86803f7adf5991774c41
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 16b0f1ba03ca50c16df5019ca7ac8d59
    md5: 1d920833c8cdf72bbee3d0032389d3eb
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ocean/ocean_tracer.res
  hashes:
    binhash: c60ff341f3848ff326c1342e0d60e32f
    md5: 51425b1323400a61451bd08a37ad02a0
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b94498c2e31eb30fe8b2e724968fc8ab
    md5: ecf36c5a38e08be5c339cd9cd0469254
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermal/restart1031/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 3bbc5139e15d5086508791e5c20f1a43
    md5: 19d42f65dfe0361cd35ed7eea8550cfe
