format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/accessom2_restart.nml
  hashes:
    binhash: ae93205aa111069250b01b754e160e41
    md5: e3e0960963cab2ef25d9695b46c2a339
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ice/grid.nc
  hashes:
    binhash: 9869ef4319d5c1072f6f3e314655ef4d
    md5: 189f572cf886440edd5ac6dab40df3d8
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ice/i2o.nc
  hashes:
    binhash: 538240c7fb900b3162a337533c5ba1f9
    md5: 804aebbe440e66f5eae364ff670d07e1
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ice/ice.restart_file
  hashes:
    binhash: e0de11a97dbfa98c50bec6cb5ff25086
    md5: c1f989020a818a6527b5482e718815f4
work/ice/RESTART/iced.2150-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ice/iced.2150-01-01-00000.nc
  hashes:
    binhash: ef8ac53076acefc21733591924cb4ddc
    md5: de9e1ad57381ba5afc8fc9a792da4786
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ice/kmt.nc
  hashes:
    binhash: 421f5c02d76914c41e0fd97ecb6893eb
    md5: a46c01045f519b9002b10f82df6ad376
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ice/monthly_sstsss.nc
  hashes:
    binhash: 213ebb6e5d98ec306ff49ec99a09e4d1
    md5: e00d77cf7b519d9bbcfc8bea2e34ef8f
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ice/o2i.nc
  hashes:
    binhash: 0411c0a4dad0b81ddd9afffed886677a
    md5: 9b0ac0fbdc2871767c8f6bbb45b6323c
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ice/sicemass.nc
  hashes:
    binhash: 9607c2bc9cad611901122757ae7f9b2f
    md5: 004e67480023ebfa98477f41724117c1
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ice/u_star.nc
  hashes:
    binhash: 3d5243451ff86ae61150f088b573364f
    md5: c2c75e0e015702fee27f79b2ad182c10
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ocean/ocean_age.res.nc
  hashes:
    binhash: cca490c8ecc44e02d5e3595634252bf5
    md5: 6a1903baf3d07f41a7209d80dce6d5b3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 82c01b2d353722c3ebd2b0728b1b4028
    md5: 30d4a1a160d047e3c529a470fabbf74c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8e77567461bb1743054bfd5135b731d1
    md5: 9ac8e854e1589bde0239d9d39f465085
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ocean/ocean_density.res.nc
  hashes:
    binhash: bf307a86936118492667e6b1846bfa1c
    md5: eaf5d2ad86cfcbed8b4ba632e80e2205
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ocean/ocean_frazil.res.nc
  hashes:
    binhash: dec7e17f2b486a4c83d791c59e85adcb
    md5: b99e0a7b1ccc698597789e191cb20bf6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 47db248506c136079539165e7cd27a52
    md5: 5763f2e84f7f950441145e5efc5d234c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 3604d00939e2147a8da66a299c548259
    md5: 117b321bc1065ee3ae463646eb5d705a
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ocean/ocean_solo.res
  hashes:
    binhash: f56edc95146ac66fd6103babdb5190e4
    md5: 9c04be22424e399a7e9fefcd55a727dc
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: b933254a3d6de761e83561c4b2993609
    md5: 6d9e5bc1aac361b011b944c512df996d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 79498d90a886c1a2db8aa4586eb7d9f5
    md5: 7a549153a7e09e9ca95b02f156a43f04
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ocean/ocean_tracer.res
  hashes:
    binhash: 1c4b02fc969ffd51a3d85a55fe9d4f40
    md5: 2e2225edc5ddaf3c63113295bd9c0b84
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 59982113fd1f371b62c118748867f7d0
    md5: f797b7edb645e2d76444fb37b0522a92
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp245_windthermal/restart995/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 40c5c045ca661ace00b3f82bcb198738
    md5: 2168e5dc41fb071cf8e333234889d9ae
