format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/accessom2_restart.nml
  hashes:
    binhash: 73c97a1ba0fd97ad395af853bcad9117
    md5: e3e0960963cab2ef25d9695b46c2a339
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ice/grid.nc
  hashes:
    binhash: 47cab3e86960a028b6c535b3a01d351b
    md5: 189f572cf886440edd5ac6dab40df3d8
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ice/i2o.nc
  hashes:
    binhash: f45d28e9e983ab7647e2126286d89082
    md5: 804aebbe440e66f5eae364ff670d07e1
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ice/ice.restart_file
  hashes:
    binhash: 82f17aedfdfde926cb5710d0133a35d9
    md5: c1f989020a818a6527b5482e718815f4
work/ice/RESTART/iced.2150-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ice/iced.2150-01-01-00000.nc
  hashes:
    binhash: 127ed1f9ff4078f15558c7acf474175c
    md5: de9e1ad57381ba5afc8fc9a792da4786
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ice/kmt.nc
  hashes:
    binhash: 16f779510953e1c4b058989d10f75148
    md5: a46c01045f519b9002b10f82df6ad376
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ice/monthly_sstsss.nc
  hashes:
    binhash: 95442f4154bb2c7c763d99164fab6650
    md5: e00d77cf7b519d9bbcfc8bea2e34ef8f
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ice/o2i.nc
  hashes:
    binhash: 7ba303fdd41d7de2d00a75baef458fd2
    md5: 9b0ac0fbdc2871767c8f6bbb45b6323c
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ice/sicemass.nc
  hashes:
    binhash: efd7f33f7bbcc89be89f39311ea40ce8
    md5: 004e67480023ebfa98477f41724117c1
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ice/u_star.nc
  hashes:
    binhash: 1420a3c3e23966389d4a2be8a3268c51
    md5: c2c75e0e015702fee27f79b2ad182c10
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ocean/ocean_age.res.nc
  hashes:
    binhash: 9983584f2da2d069409f28936b0cc743
    md5: 6a1903baf3d07f41a7209d80dce6d5b3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ba06554947bd7e29fa2871d8d70baf76
    md5: 30d4a1a160d047e3c529a470fabbf74c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 383fac126ca4db6f1bcb423e030f07b3
    md5: 9ac8e854e1589bde0239d9d39f465085
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ocean/ocean_density.res.nc
  hashes:
    binhash: 111e6c69c07e788c6be71879b852b6fc
    md5: eaf5d2ad86cfcbed8b4ba632e80e2205
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 278c0e9bc027212e2fbb82149b636a8d
    md5: b99e0a7b1ccc698597789e191cb20bf6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e5a21c944d156a8d648a552bcf813b56
    md5: 5763f2e84f7f950441145e5efc5d234c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ocean/ocean_sbc.res.nc
  hashes:
    binhash: daf99f0667bd40bd0be522d7302d4b99
    md5: 117b321bc1065ee3ae463646eb5d705a
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ocean/ocean_solo.res
  hashes:
    binhash: 3d7239319d4d9d02ec8b0ba9895d2a93
    md5: 9c04be22424e399a7e9fefcd55a727dc
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1e6699d0bf76ac44608e159961b420dd
    md5: 6d9e5bc1aac361b011b944c512df996d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8607a6b731ad534f3bda93dcff8ebc71
    md5: 7a549153a7e09e9ca95b02f156a43f04
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ocean/ocean_tracer.res
  hashes:
    binhash: c442a5b9e9562800093bd00586071427
    md5: 2e2225edc5ddaf3c63113295bd9c0b84
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 63368ab65bdef5607e88d560ba330f6c
    md5: f797b7edb645e2d76444fb37b0522a92
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/hd4873/access-om2/archive/01deg_jra55v13_ssp585_windthermalmw/restart995/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6b4470ba5a19fd8455708965ef569ab7
    md5: 2168e5dc41fb071cf8e333234889d9ae
